### ISSUE TITLE
great work

### ISSUE THREAD

**Issue by xingzheone** [Gonzih/glue#1]
Thank you for your hard work :)

**Comment by Gonzih** [comment]
you are welcome, please try this wrapper out and tell me what do you 
think. I would love to optimize notifications inside components better, 
but Vue does not expose internal classes yet. Maybe it will change one 
day (for more details take a look at vuejs/vue#5258).

**Comment by xingzheone** [comment]
ok ,  Strongly suggested test with  https://github.com/marick/Midje . this is Excellent .

**Comment by Gonzih** [comment]
Sorry, i really dislike midje extra complexity, cljs.test just works and im 
fine with that.

**Comment by mitar** [comment]
You might be able to use [this package](https://www.npmjs.com/package/@tozd/vue-observer-utils) I made to get access to internal classes.

**Comment by aadrian** [comment]
@Gonzih any chance getting some updates? Or was it just an experiment?

**Comment by Gonzih** [comment]
@mitar that might be useful indeed, thanks
@aadrian this is not on my radar atm, but I would be happy to take any incoming PRs :)
